name: Scheduled Reusable Runner

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch: {}

jobs:
  run-reusable:
    uses: ${{ github.repository_owner }}/${{ github.repository }}/.github/workflows/scheduled-reusable.yaml@main
    with:
      message: "Scheduled run: hello from reusable workflow"
