name: Scheduled Reusable Runner

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  run-reusable:
    uses: ./.github/workflows/scheduled-reusable.yaml
    with:
      message: "Scheduled run: hello from reusable workflow"
