name: Scheduled Reusable Runner

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:
    inputs:
      storage:
        description: "Storage"
        required: false
        type: choice
        default: s3
        options:
          - s3
          - gcs
          - azure
          - oss

defaults:
  run:
    shell: bash

jobs:
  run-reusable:
    uses: ./.github/workflows/scheduled-reusable.yaml
    with:
      # message: "Scheduled run: hello from reusable workflow"
      message: "test run"
  
  print-file-content:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: test cat
        run: |
          cat test.txt
          echo "${{ github.event.inputs.storage }}"
